const Map<String, String> ar_EG = {
  "welcome_text": "مرحبًا بك في Coach Dealer",
  "choose_language": "يرجى اختيار اللغة",
  "login_to_your_account": "تسجيل الدخول إلى حسابك",
  "enter_phone_number_to_login": "أدخل رقم هاتفك لتسجيل الدخول",
  "phone_number": "رقم الهاتف",
  "login": "تسجيل الدخول",
  "not_have_account": "ليس لديك حساب؟",
  "create_account": "إنشاء حساب",
  "phone_number_validator": "يرجى إدخال رقم هاتف صالح",
  "register_subtitle": "أدخل البيانات المطلوبة لإنشاء حسابك",
  "name": "الاسم",
  "name_hint": "أدخل اسمك",
  "name_validator": "يرجى إدخال اسم صحيح لا يقل عن 3 أحرف",
  "verify": "تحقق",
  "already_have_account": "هل لديك حساب بالفعل؟",
  "phone_verification": "التحقق من الهاتف",
  "enter_otp_code": "أدخل رمز التحقق المرسل إلى هاتفك",
  "didnt_receive_code": "لم يصلك الرمز؟",
  "resend_code": "إعادة إرسال الرمز",
  "confirm": "تأكيد",
  "enter_otp": "يرجى إدخال رمز التحقق",
  "welcome": "مرحبًا",
  "search": "بحث",
  "store_offers": "عروض المتجر",
  "new_coaches": "مدربون جدد",
  "new_clubs": "أندية جديدة",
  "add_to_cart": "أضف إلى السلة",
  "see_all": "عرض الكل",
  "coaches": "المدربون",
  "all_coaches": "جميع المدربين",
  "clubs": "الأندية",
  "all_clubs": "جميع الأندية",
  "events": "الفعاليات",
  "store": "المتجر",
  "all_products": "جميع المنتجات",
  "event_details": "تفاصيل الفعالية",
  "details": "التفاصيل",
  "subscribe": "اشترك",
  "see_location": "عرض الموقع",
  "account": "الحساب",
  "booking_and_subscriptions": "الحجوزات والاشتراكات",
  "store_orders": "طلبات المتجر",
  "favorites": "المفضلة",
  "my_address": "عنواني",
  "settings": "الإعدادات",
  "rules_and_condition": "الشروط والأحكام",
  "contact_us": "اتصل بنا",
  "privacy_policy": "سياسة الخصوصية",
  "logout": "تسجيل الخروج",
  "edit_profile": "تعديل الملف الشخصي",
  "weight": "الوزن",
  "tall": "الطول",
  "gender": "الجنس",
  "age": "العمر",
  "health_problems": "مشاكل صحية",
  "if_exists": "إن وجد",
  "save_changes": "حفظ التغييرات",
  "club_profile": "ملف النادي",
  "see_working_hours": "عرض ساعات العمل",
  "bio": "نبذة",
  "sports": "الرياضات",
  "working_hours": "ساعات العمل",
  "contact_us_desc": "إذا كان لديك أي استفسارات أو شكاوى لا تتردد في الاتصال بنا",
  "email": "البريد الإلكتروني",
  "email_hint": "أدخل بريدك الإلكتروني",
  "contact_us_field": "الرسالة / سبب الاتصال",
  "contact_us_field_hint": "اكتب رسالتك هنا",
  "or": "أو",
  "language": "اللغة",
  "notifications": "الإشعارات",
  "add_new_address": "إضافة عنوان جديد",
  "edit_address": "تعديل العنوان",
  "location": "الموقع",
  "location_hint": "تحديد الموقع",
  "city": "المدينة",
  "select_city": "اختر المدينة",
  "region": "المنطقة",
  "select_region": "اختر المنطقة",
  "block": "الحي",
  "block_hint": "أدخل رقم/اسم الحي",
  "street_name": "اسم الشارع",
  "street_name_hint": "أدخل اسم الشارع",
  "building_no": "رقم المبنى",
  "building_number_hint": "أدخل رقم/اسم المبنى",
  "add": "إضافة",
  "something_went_wrong": "حدث خطأ ما",
  "male": "ذكر",
  "female": "أنثى",
  "profile_updated_successfully": "تم تحديث الملف الشخصي بنجاح",
  "send": " إرسال",
  "email_validator": "يرجى إدخال بريد إلكتروني صالح",
  "message_validator": "يرجى إدخال رسالة",
  "complete_profile": "أكمل ملفك الشخصي",
  "add_your_bio": "أضف نبذة عنك",
  "trainees_numbers": "عدد المتدربين",
  "sessions_numbers": "عدد الجلسات",
  "experience_years": "سنوات الخبرة",
  "experience_in": "الخبرة في",
  "select_sport": "اختر نوع الرياضة",
  "enter_session_fees": "أدخل رسوم الجلسة",
  "add_sport": "+ أضف رياضة",
  "working_days": "أيام العمل",
  "select_working_days": "اختر أيام العمل",
  "class_period_in_minutes": "مدة الحصة بالدقائق",
  "enter_class_period_in_minutes": "أدخل مدة الحصة بالدقائق",
  "first_shift_hours_period": "فترة دوام الشفت الأول",
  "from": "من",
  "to": "إلى",
  "add_shift": "+ أضف شفت",
  "gallery_images": "صور المعرض",
  "add_images": "أضف صور",
  "save": "حفظ",
  "enter_number": "ادخل الرقم",
  "enter_your_name": "أدخل اسمك",
  "saturday": "السبت",
  "sunday": "الأحد",
  "monday": "الاثنين",
  "tuesday": "الثلاثاء",
  "wednesday": "الأربعاء",
  "thursday": "الخميس",
  "friday": "الجمعة",
  "empty_field": "يرجى ملء هذا الحقل",
  "todays_bookings": "حجوزات اليوم",
  "class_date": "تاريخ الحصة",
  "bookings_history": "سجل الحجوزات",
  "rules_and_conditions": "الشروط والأحكام",
  "last_week": " الأسبوع الماضي",
  "last_month": "الشهر الماضي",
  "last_3_month": "آخر 3 أشهر",
  "last_year": "السنة الماضية",
  "no_bookings": "لا توجد حجوزات",
  "booking_details": "تفاصيل الحجز",
  "class_details": "تفاصيل الحصة",
  "class_type": "نوع الحصة",
  "class_time": "وقت الحصة",
  "payment_method": "طريقة الدفع",
  "price_summary": "ملخص السعر",
  "class_booking_fees": "رسوم الحجز",
  "discount": "الخصم",
  "total": "الإجمالي",
};
