const Map<String, String> en_US = {
  'welcome_text': 'Welcome to Coach Dealer',
  "choose_language": "Please Choose Language",
  "login_to_your_account": "Login to your account",
  "enter_phone_number_to_login": "Enter your phone number to login",
  "phone_number": "Phone Number",
  "login": "Login",
  "not_have_account": "Don't have an account?",
  "create_account": "Create account",
  "phone_number_validator": "Please enter valid phone number",
  "register_subtitle": "Enter required data to create your account",
  "name": "Name",
  "name_hint": "Enter your name",
  "name_validator": "Please enter valid name at least 3 characters",
  "verify": "Verify",
  "already_have_account": "Already have an account?",
  "phone_verification": "Phone Verification",
  "enter_otp_code": "Enter the OTP code sent to your phone",
  "didnt_receive_code": "Didn’t receive the code?",
  "resend_code": "Resend Code",
  "confirm": "Confirm",
  "enter_otp": "Please Enter otp",
  "welcome": "Welcome",
  "search": "Search",
  "store_offers": "Store Offers",
  "new_coaches": "New Coaches",
  "new_clubs": "New Clubs",
  "add_to_cart": "Add to Cart",
  "see_all": "See all",
  "coaches": "Coaches",
  "all_coaches": "All Coaches",
  "clubs": "Clubs",
  "all_clubs": "All Clubs",
  "events": "Events",
  "store": "Store",
  "all_products": "All Products",
  "event_details": "Event Details",
  "details": "Details",
  "subscribe": "Subscribe",
  "see_location": "See Location",
  "account": "Account",
  "booking_and_subscriptions": "Bookings & Subscriptions",
  "store_orders": "Store Orders",
  "favorites": "Favorites",
  "my_address": "My Address",
  "settings": "Settings",
  "rules_and_condition": "Rules & Conditions",
  "contact_us": "Contact Us",
  "privacy_policy": "Privacy Policy",
  "logout": "Logout",
  "edit_profile": "Edit Profile",
  "weight": "Weight",
  "tall": "Tall",
  "gender": "Gender",
  "age": "Age",
  "health_problems": "Health Problems",
  "if_exists": "If exists",
  "save_changes": "Save Changes",
  "club_profile": "Club Profile",
  "see_working_hours": "See Working Hours",
  "bio": "Bio",
  "sports": "Sports",
  "working_hours": "Working Hours",
  "contact_us_desc": "If you have any questions or complaints do not hesitate to contact us",
  "email": "E-mail",
  "email_hint": "Enter your E-mail",
  "contact_us_field": "Message/Reason Of Contact",
  "contact_us_field_hint": "Write your message here",
  "or": "OR",
  "language": "Language",
  "notifications": "Notifications",
  "add_new_address": "Add New Address",
  "edit_address": "Edit Address",
  "location": "Location",
  "location_hint": "Detect Location",
  "city": "City",
  "select_city": "Select City",
  "region": "Region",
  "select_region": "Select Region",
  "block": "Block",
  "block_hint": "enter block no./name",
  "street_name": "Street Name",
  "street_name_hint": "enter street name",
  "building_no": "Building No.",
  "building_number_hint": "enter building no./name",
  "add": "Add",
  "coach_profile": "Coach Profile",
  "book_class": "Book a class",
  "trainees": "Trainees",
  "sessions": "Sessions",
  "exp": "Exp",
  "gallery": " Gallery",
  "class_category": "Class Category",
  "class_category_hint": "Select Class Category",
  "select_date": "Select Date",
  "select_time": "Select Time",
  "confirm_booking": "Confirm Booking",
  "check_out": "Check Out",
  "booking_class": "Booking Class",
  "payment_method": "Payment Method",
  "coupon": "Coupon",
  "apply": "Apply",
  "enter_coupon": "Enter Coupon",
  "price_summary": "Price Summary",
  "class_booking_fees": "Class Booking Fees",
  "discount": "Discount",
  "total": "Total",
  "pay": "Pay",
  "something_went_wrong": "Something went wrong",
  "male": "Male",
  "female": "Female",
  "profile_updated_successfully": "Profile updated successfully",
  "send": " Send",
  "email_validator": "Please enter valid email",
  "message_validator": "Please enter valid message at least 10 characters",
  "complete_profile": "Complete Profile",
  "add_your_bio": "Add your bio",
  "trainees_numbers": "Trainees Numbers",
  "sessions_numbers": "Sessions Numbers",
  "experience_years": "Experience Years",
  "experience_in": "Experience in",
  "select_sport": "Select sport",
  "enter_session_fees": "Enter session fees",
  "add_sport": "+ Add Sport",
  "working_days": "Working Days",
  "select_working_days": "Select working days",
  "class_period_in_minutes": "Class Period In Minutes",
  "enter_class_period_in_minutes": "Enter class period in minutes",
  "first_shift_hours_period": "First Shift Hours Period",
  "from": "From",
  "to": "To",
  "add_shift": "+ Add Shift",
  "gallery_images": "Gallery Images",
  "add_images": "Add Images",
  "save": "Save",
  "enter_number": "Enter number",
  "enter_your_name": "Enter your name",
  "saturday": "Saturday",
  "sunday": "Sunday",
  "monday": "Monday",
  "tuesday": "Tuesday",
  "wednesday": "Wednesday",
  "thursday": "Thursday",
  "friday": "Friday",
  "empty_field": "Please fill this field",
  "todays_bookings": "Today’s Bookings",
  "class_date": "Class Date",
  "bookings_history": "Bookings History",
  "rules_and_conditions": "Rules & Conditions",
  "last_week": "Last Week",
  "no_bookings": "No Bookings",
  "booking_details": "Booking Details",
  "class_details": "Class Details",
  "class_type": "Class Type",
  "class_time": "Class Time",
};
